# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sudhagar
email: sudhagar@isudhagar.in
description: > # this means to ignore newlines until "baseurl:"
  Been coding ever since I got fascinated by computers. Language Junkie. 
  Sometimes I obsess over understanding how things work under the hood.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: shotwhat
github_username:  sudhagars

# Build settings
markdown: kramdown
